id: walnut.proxmox.ve
name: Proxmox VE
version: 1.0.1
category: host-orchestrator
min_core_version: "0.10.0"

driver:
  entrypoint: driver:ProxmoxVeDriver
  language: python
  runtime: embedded

schema:
  connection:
    type: object
    required: [host, port, node, api_token]
    properties:
      host: { type: string, title: Host }
      port: { type: integer, default: 8006 }
      token_name: { type: string, title: Token Name }   # e.g. "user@pam!tokenid"
      node: { type: string, title: Node }
      verify_ssl: { type: boolean, default: true }
      api_token: { type: string, secret: true, title: API Token }  # token secret

defaults:
  http:
    timeout_s: 5
    retries: 2
    backoff_ms_start: 250
    verify_tls: true
  heartbeat_interval_s: 120
  dry_run_refresh_sla_s: 5

test:
  method: http
  http:
    request:
      method: GET
      path: /version
    success_when: "status == 200"

capabilities:
  - id: vm.lifecycle
    verbs: [shutdown, start, stop, suspend, resume, reset]
    targets: [vm]
    dry_run: required
    invertible:
      start:
        inverse: shutdown
      shutdown:
        inverse: start
    idempotency:
      key_fields: [verb, target_id]

  - id: power.control
    verbs: [shutdown, cycle]   # cycle = reboot intent
    targets: [host]
    dry_run: required
    idempotency:
      key_fields: [verb, target_id]

  - id: inventory.list
    verbs: [list]
    targets: [vm, host]
    dry_run: optional
